#!/bin/bash

set -o errexit 
set -o pipefail 
set -o nounset 

if [ -z "${POSTGRES_USER}" ]; then 
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi 

# exporting the db url here. not needed in compose file or in add expandable dict in the settings. 
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

# check postgres availability
python << END
import sys 
import time 
import psycopg2

suggest_postgres_unrecoverable_after_time = 30
start_time = time.time()

while True: 
    try: 
        psycopg2.connect(
            dbname="${POSTGRES_DB}", 
            user="${POSTGRES_USER}", 
            password="${POSTGRES_PASSWORD}", 
            host="${POSTGRES_HOST}", 
            port="${POSTGRES_PORT}",
        )
        break
    except psycopg2.OperationalError as err: 
        sys.stderr.write("Waiting for PostgreSQL to become available ... \n")
        if time.time() - start_time > suggest_postgres_unrecoverable_after_time: 
            sys.stderr.write("This is taking longer than expected. The following may be the root cause "
            "for the error: '{}'\n".format(err))
    time.sleep(1)
END

>&2 echo "PostgresSQL is available"

# check mongbd availability  
export MONGO_HOST=${MONGO_HOST}
export MONGO_PORT=${MONGO_PORT}
export MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
export MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
export MONGO_AUTH_SOURCE_DB=${MONGO_AUTH_SOURCE_DB}


python3 << END
import sys
import time
import os
import pymongo
from pymongo import MongoClient

suggest_mongo_unrecoverable_after_time = 30
start_time = time.time()

while True:
    try:
        client = MongoClient(
            host=os.environ.get('MONGO_HOST'),
            port=int(os.environ.get('MONGO_PORT')),
            username=os.environ.get('MONGO_INITDB_ROOT_USERNAME'),
            password=os.environ.get('MONGO_INITDB_ROOT_PASSWORD'),
            authSource=os.environ.get('MONGO_AUTH_SOURCE_DB'),
        )
        break
    except pymongo.errors.ConnectionFailure as err:
        sys.stderr.write("Waiting for MongoDb to become available ... \n")
        if time.time() - start_time > suggest_mongo_unrecoverable_after_time:
            sys.stderr.write("This is taking longer than expected. The following may be the root cause "
                             "for the error: '{}'\n".format(err))
    time.sleep(1)
END

>&2 echo "MongoDB is available"

exec "$@"
